import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  textbookSidebar: [
    {
      type: 'autogenerated',
      dirName: 'rigorous-probability',
    },
  ],
};

export default sidebars;
